# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DecibelMet' do

  pod 'KDCircularProgress'
  pod 'Charts'
 
  pod 'SwipeCellKit'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'DKCamera'
   pod 'OpenSSL', '~> 1.0'
end
